- name: loops
  hosts: web
  become: yes # become:yes means, becoming root user and it got sudo privilages
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{item}}" # item is a default keyword
      state: present # state=present means install
    loop:
    - git
    - mysql
    - nginx 
  - name: start Nginx
    service:     
      name: nginx
      state: started   
    