- name: loops
  hosts: web
  tasks:
  - name: print persons
    ansible.builtin.debug:
      msg: "Hello {{item}}" # item is a default keyword
    loop:
    - Arun
    - Abhi
    - Srikant
    - sathi
    - subbi
    
